services:
  - type: web
    name: chatgpt-backend
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CLIENT_URL
        value: https://your-frontend-url.netlify.app
